# Job name
name: Greeting first time users

# When the to run the greeting
on: [pull_request, issues]

# Jobs to run for the action (You can have multiple actions in one file)
jobs:
  greet-user:
    # Job display name
    name: Greeting Action

    # Runs on a Linux based OS
    runs-on: ubuntu-latest

    # Runs the greeting action (Options can be found here https://github.com/actions/first-interaction)
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }} # Authorizes the github action via a Github token which is for this repo only (Generated automatically)
          issue-message: "Looks like this is your first issue' first issue" # Shows when a user fires their first issue
          pr-message: "Looks like this is your first PR' first pr" # Shows when a user fires their first PR
